### ISSUE TITLE
Empty version 0.0 is on PyPi

### ISSUE THREAD

**Issue by spiralx** [jgorset/facebook#3]
The version up at the Python Package Index is version 0.0, featuring a single `__init__.py` file with the following code:

```py
"""TODO: Document your package."""

__version__ = 'TODO: Enter a version'
```

Any chance of updating the code there as it's a bit pointless, especially as it's the top result returned if you search for Facebook? Thanks!

https://pypi.python.org/pypi/Facebook

**Comment by jgorset** [comment]
Hi @spiralx! I could bump the version to 0.0.1 and push that, but I'm not sure it would do you much good; either way this library really doesn't do much, and it probably [never will](https://github.com/jgorset/facebook/commit/10ccba4be400ff1e3785a1f18e56223143dca950). 

I think you'd like [facepy](https://github.com/jgorset/facepy), though - perhaps a better thing to do would be to update the README and description on the Python Package Index to point you in that direction?

**Comment by spiralx** [comment]
Sorry for not getting back sooner, cheers for the response. Either option would work, or both :) Thanks for the link!
