### ISSUE TITLE
Doesn't work anymore?

### ISSUE THREAD

**Issue by naeem-hasan** [jgorset/facebook#4]
Hi! I couldn't seem to make it work. I couldn't get my own ID's first_name, even with an access token.
The error at the end is:
facepy.exceptions.OAuthError: [803] (#803) Cannot query users by their username (wizard.naeemhasan)

**Comment by jgorset** [comment]
I think this [hardly ever worked](https://github.com/jgorset/facebook#disclaimer), actually. Try [jgorset/facepy](http://github.com/jgorset/facepy), though. ;-)
